#!/bin/sh
#
# backup: Overrides the `container-backup()` function from the upstream container
#         this file should be coppied to /etc/container/backup` via the 'Containerfile`.

container_backup() {
 /usr/bin/sqlite3 /mnt/volumes/container/core.sqlite ".backup 'backup.sq3'"
 /bin/cp /etc/container/drone-server.env ./
}
