#!/bin/sh
#
# backup: Overrides the `container-backup()` function from the upstream container
#         this file should be coppied to /etc/container/backup` via the 'Containerfile`.

container_backup() {
 /usr/bin/sqlite3 /opt/drone/core.sqlite ".backup 'drone_core_backup.sq3'"
}
