version: "3.9"
services:
  drone:
    build:
      args:
        ALPINE_VERSION: "latest"
        DRONE_SERVER_VERSION: 2.16.0
        CONTAINER_VERSION: 2.16.0
      context: .
      dockerfile: Containerfile
      no_cache: true
      tags:
        - "drone:build"
    environment:
      - SYSTEM_ENVIRONMENT=DEVELOPMENT
    hostname: "drone"
    image: "gautada/drone:build"
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - "container:/mnt/volumes/container"
      - "backup:/mnt/volumes/backup"
        
volumes:
  container:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/drone/container-volume
  backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/drone/backup-volume
      
