version: "3.9"
services:
  drone:
    build:
      args:
        ALPINE_VERSION: "latest"
        PODMAN_VERSION: "4.1.0"
        DRONE_SERVER_VERSION: "2.11.1"
        DRONE_CLI_VERSION: "1.5.0"
        DRONE_RUNNER_DOCKER_VERSION: "1.8.1"
        DRONE_RUNNER_EXEC_VERSION: "1.0.0-beta.9"
        DRONE_RUNNER_KUBE_VERSION: "1.0.0-rc.3"
      context: .
      dockerfile: Containerfile
      no_cache: true
      tags:
        - "drone:dev"
    image: "drone:dev"
    ports:
      - "8080:8080"
    volumes:
      - "development:/opt/drone"
      - "backup:/opt/backup"
        
volumes:
  development:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/drone/development-volume
  backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/drone/backup-volume
      
