version: "3.9"
services:
  drone:
    build:
      args:
        ALPINE_VERSION: "latest"
        PODMAN_VERSION: "4.3.0"
        DRONE_SERVER_VERSION: 2.16.0
        DRONE_CLI_VERSION: 1.7.0
        DRONE_RUNNER_DOCKER_VERSION: 1.8.3
        DRONE_RUNNER_EXEC_VERSION: 1.0.0-beta.10
        DRONE_RUNNER_KUBE_VERSION: 1.0.0-rc.3
      context: .
      dockerfile: Containerfile
      no_cache: true
      tags:
        - "drone:dev"
    image: "drone:dev"
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - "container:/mnt/volumes/container"
      - "backup:/mnt/volumes/backup"
        
volumes:
  container:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/drone/container-volume
  backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/drone/backup-volume
      
