kind: pipeline
type: kubernetes
name: Continuous Integration

steps:
- name: arm-build
  image: docker.io/gautada/builder:3.2.3-r1
  privileged: true
  environment:
    PODMAN_KEY:
      from_secret: podman.key
    PODMAN_CERT:
      from_secret: podman.cert
    ALPINE_TAG: 3.14.2
    SERVER_BRANCH: v2.3.1
    RUNNER_BRANCH: v1.0.0-beta.12
    CLI_BRANCH: v1.4.0
  commands:
  - /builder-base 5
  - podman --remote --connection arm build --build-arg ALPINE_TAG=$ALPINE_TAG --build-arg SERVER_BRANCH=$SERVER_BRANCH --build-arg RUNNER_BRANCH=$RUNNER_BRANCH --build-arg CLI_BRANCH=$CLI_BRANCH --file Containerfile --format docker --no-cache --platform linux/arm64/v8 --tag drone:dev .

- name: x86-build
  image: docker.io/gautada/builder:3.2.3-r1
  privileged: true
  environment:
    DOCKERIO_USERNAME:
      from_secret: username.docker.io
    DOCKERIO_PASSWORD:
      from_secret: password.docker.io
    PODMAN_KEY:
      from_secret: podman.key
    PODMAN_CERT:
      from_secret: podman.cert
    ALPINE_TAG: 3.14.2
    SERVER_BRANCH: v2.3.1
    RUNNER_BRANCH: v1.0.0-beta.12
    CLI_BRANCH: v1.4.0
  commands:
  - /builder-base 5
  - podman --remote --connection x86 build --build-arg ALPINE_TAG=$ALPINE_TAG --build-arg SERVER_BRANCH=$SERVER_BRANCH --build-arg RUNNER_BRANCH=$RUNNER_BRANCH --build-arg CLI_BRANCH=$CLI_BRANCH --file Containerfile --format docker --no-cache --platform linux/arm64/v8 --tag drone:dev .

- name: arm-push
  image: docker.io/gautada/builder:3.2.3-r1
  privileged: true
  environment:
    DOCKERIO_USERNAME:
      from_secret: username.docker.io
    DOCKERIO_PASSWORD:
      from_secret: password.docker.io
    PODMAN_KEY:
      from_secret: podman.key
    PODMAN_CERT:
      from_secret: podman.cert
    SERVER_BRANCH: v2.3.1
  commands:
  - /builder-base 5
  - podman --remote --connection arm tag podman:dev docker.io/gautada/drone:arm-$SERVER_BRANCH
  - podman --remote --connection arm login --username=$DOCKERIO_USERNAME --password=$DOCKERIO_PASSWORD docker.io
  - podman --remote --connection arm push docker.io/gautada/drone:arm-$SERVER_BRANCH

- name: arm-push
  image: docker.io/gautada/builder:3.2.3-r1
  privileged: true
  environment:
    DOCKERIO_USERNAME:
      from_secret: username.docker.io
    DOCKERIO_PASSWORD:
      from_secret: password.docker.io
    PODMAN_KEY:
      from_secret: podman.key
    PODMAN_CERT:
      from_secret: podman.cert
    SERVER_BRANCH: v2.3.1
  commands:
  - /builder-base 5
  - podman --remote --connection x86 tag podman:dev docker.io/gautada/drone:x86-$SERVER_BRANCH
  - podman --remote --connection x86 login --username=$DOCKERIO_USERNAME --password=$DOCKERIO_PASSWORD docker.io
  - podman --remote --connection x86 push docker.io/gautada/drone:x86-$SERVER_BRANCH

- name: manifest-create
  image: docker.io/gautada/builder:3.2.3-r1
  privileged: true
  environment:
    DOCKERIO_USERNAME:
      from_secret: username.docker.io
    DOCKERIO_PASSWORD:
      from_secret: password.docker.io
    PODMAN_KEY:
      from_secret: podman.key
    PODMAN_CERT:
      from_secret: podman.cert
    SERVER_BRANCH: v2.3.1
  commands:
  - /builder-base 5
  - podman --remote --connection arm manifest create drone:man
  - podman --remote --connection arm manifest add drone:man docker.io/gautada/drone:arm-$SERVER_BRANCH
  - podman --remote --connection arm manifest add drone:man docker.io/gautada/drone:x86-$SERVER_BRANCH
  - podman --remote --connection arm tag drone:man docker.io/gautada/drone:$SERVER_BRANCH
  - podman --remote --connection arm login --username=$DOCKERIO_USERNAME --password=$DOCKERIO_PASSWORD docker.io
  - podman --remote --connection arm push docker.io/gautada/drone:$SERVER_BRANCH
  
- name: clean
  image: docker.io/gautada/builder:3.2.3-r1
  privileged: true
  environment:
    DOCKERIO_USERNAME:
      from_secret: username.docker.io
    DOCKERIO_PASSWORD:
      from_secret: password.docker.io
    PODMAN_KEY:
      from_secret: podman.key
    PODMAN_CERT:
      from_secret: podman.cert
    SERVER_BRANCH: v2.3.1
  commands:
  - /builder-base 5
  - podman --remote --connection arm rmi drone:man
  - podman --remote --connection arm rmi docker.io/gautada/drone:arm-$SERVER_BRANCH
  - podman --remote --connection x86 rmi drone:dev
  - podman --remote --connection x86 rmi docker.io/gautada/drone:x86-$SERVER_BRANCH
  - podman --remote --connection arm rmi drone:man
  - podman --remote --connection x86 rmi docker.io/gautada/drone:$SERVER_BRANCH

trigger:
  branch:
  - dev


