kind: pipeline
type: exec
name: CICD - Container Build

platform:
  os: linux
  arch: arm64

steps:
- name: build
  commands:
  - /usr/sbin/image-build
  - /usr/bin/podman images

- name: publish(test)
  environment:
    DOCKERIO_USERNAME:
      from_secret: username.docker.io
    DOCKERIO_PASSWORD:
      from_secret: password.docker.io
    PUBLISH_REPOSITORY:
      value: docker.io
  commands:
  - pwd
  - /usr/sbin/image-name
  - /usr/sbin/image-tag test
  - /usr/sbin/image-publish test
  

trigger:
  event:
  - push
  




  
