kind: pipeline
type: kubernetes
name: Continuous Integration

steps:
- name: build-arm
  image: docker.io/gautada/builder:3.2.3-r1-arm
  privileged: true
  environment:
    DOCKER_USERNAME:
      from_secret: username.docker.io
    DOCKER_PASSWORD:
      from_secret: password.docker.io
    PODMAN_KEY_ARM:
      from_secret: podman.key.arm
    PODMAN_CERT_ARM:
      from_secret: podman.cert.arm
    PODMAN_KEY_x86:
      from_secret: podman.key.x86
    PODMAN_CERT_x86:
      from_secret: podman.cert.x86
    ALPINE_TAG: 3.14.2
    SERVER_BRANCH: v2.3.1
    RUNNER_BRANCH: v1.0.0-beta.12
    CLI_BRANCH: v1.4.0
    LIMAGE: localhost/droneci:dev
    RIMAGE: docker://docker.io/gautada/droneci:v2.3.1-aarch64
  commands:
  - /builder-base 5
  - podman --remote --connection arm build --build-arg ALPINE_TAG=3.14.2 --build-arg SERVER_BRANCH=v2.3.1 --build-arg RUNNER_BRANCH=v1.0.0-beta.12 --build-arg CLI_BRANCH=v1.4.0 --file Containerfile --no-cache  --tag drone:dev .
  - podman --remote --connection arm tag drone:dev docker.io/gautada/drone:v2.3.1-arm
  - podman --remote --connection arm login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD docker.io
  - podman --remote --connection arm push docker.io/gautada/drone:v2.3.1-arm
  - podman --remote --connection x86 build --build-arg ALPINE_TAG=3.14.2  --build-arg SERVER_BRANCH=v2.3.1 --build-arg RUNNER_BRANCH=v1.0.0-beta.12 --build-arg CLI_BRANCH=v1.4.0 --file Containerfile --no-cache  --tag drone:dev .
  - podman --remote --connection x86 tag drone:dev docker.io/gautada/drone:v2.3.1-x86
  - podman --remote --connection x86 login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD docker.io
  - podman --remote --connection x86 push docker.io/gautada/drone:v2.3.1-x86
  - podman --remote --connection arm manifest create drone:man
  - podman --remote --connection arm manifest add drone:man docker.io/gautada/drone:v2.3.1-arm
  - podman --remote --connection arm manifest add drone:man docker.io/gautada/drone:v2.3.1-x86
  - podman --remote --connection arm tag drone:man docker.io/gautada/drone:v2.3.1
  - podman --remote --connection arm login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD docker.io
  - podman --remote --connection arm push docker.io/gautada/drone:v2.3.1
  - podman --remote --connection arm rmi drone:man

trigger:
  branch:
  - dev


